---
title: "Proposal to run a BoF on Notebooks at RDA Helsinki"
---

## TL;DR 
I am putting together a proposal to run a BoF session on Notebooks (i.e. discussions on Jupyter and myBinder but if this is too narrow a scope please say so) at 
[RDA Helsinki](https://www.rd-alliance.org/rda-14th-plenary-helsinki-espoo)
which will run from 23rd-25th of October.
The deadline for the proposal is the 27th June. 

If you are interested in getting involved, then please email me 
at 

Hugh dot Shanahan at rhul dot ac dot uk. 


## Introduction
Notebooks, specifically Jupyter notebooks (but also notebooks based on Rmarkdown) are generating a great deal of excitement and are potentially a significant step forward in terms of reproducibility, education, code documentation and publications. 

More recently the deployment of sites such as JupyterHub, myBinder and EGI notebooks mean that notebooks can be deployed on a cloud and hence obviates 
issues with installed libraries. One potential result of this is that it would represent the easiest pathway for users to use 
cloud computing resources for research which could transform the use
of such resources. It is important that initiatives such as EOSC become more
aware of such initiatives at a policy level. 


As we get to a position where research computing is increasingly cloud-based this will be key and is worth dicussing at the RDA. 


## Possible discussion points for BoF

BoF's at the RDA are allocated 90 minutes. The following are a set of possible topics that could be discussed at the BoF.


### Notebook citation
Given the profusion of notebooks it is clear that a system of enabling citation of notebooks needs to be implemented. In many respects this 
represents an opportunity as the technology is comparatively new and 
hence potentially easily adapted to follow citations guidelines for 
the Force 11 software citation group. 


### Software engineering
A valid criticism of notebooks are that it encourages poor software 
engineering practice such as TDD or encapsulating the notebooks into libraries. Some of this stems from the fact that notebook editors 
are nowhere near as developed as other IDE's but the first concerns are genuine. 


### Notebooks on EOSC
The EGI already successfully deployed a notebook solution. Can the functionality of binder be similarly deployed? How do notebooks fit into the 
EOSC vision? 










